# Generated by Django 5.0 on 2024-04-14 05:43

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Listing_Title', models.CharField(max_length=40)),
                ('Listing_Image', models.ImageField(upload_to='')),
                ('field_1', models.CharField(default=True, max_length=50)),
                ('field_2', models.CharField(default=True, max_length=50)),
                ('Listing_Cost', models.FloatField()),
                ('Listing_Calories', models.CharField(max_length=10, null=True)),
                ('Listing_Descr', models.TextField(max_length=200, null=True)),
                ('Listing_Ingredients', models.TextField(max_length=200, null=True)),
                ('allergen_choices', models.CharField(choices=[('Dairy', 'Dairy'), ('Eggs', 'Eggs'), ('Gluten', 'Gluten'), ('Nuts', 'Nuts'), ('Soy', 'Soy'), ('Other', 'Other'), ('None', 'None')], default='None', max_length=6)),
                ('Listing_Tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Listing Creation',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sub_description', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
