# Generated by Django 5.0.3 on 2024-04-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_profile_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="https://via.placeholder.com/150",
                null=True,
                upload_to="profile_images/",
            ),
        ),
    ]
