# Generated by Django 5.0.3 on 2024-04-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_profile_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="Listing_Image",
            field=models.ImageField(blank=True, null=True, upload_to="Listing_Image/"),
        ),
    ]
