# Generated by Django 5.0.3 on 2024-05-02 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_listing_listing_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="Listing_Calories",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="field_2",
        ),
    ]
