# Generated by Django 5.0.3 on 2024-05-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_remove_listing_listing_calories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="Listing_Cost",
            field=models.FloatField(blank=True),
        ),
    ]
