# Generated by Django 5.0.3 on 2024-05-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_listing_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="allergen_choices",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Dairy", "Dairy"),
                    ("Eggs", "Eggs"),
                    ("Gluten", "Gluten"),
                    ("Nuts", "Nuts"),
                    ("Soy", "Soy"),
                    ("Other", "Other"),
                    ("None", "None"),
                ],
                default="None",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="field_1",
            field=models.CharField(blank=True, default=True, max_length=50),
        ),
    ]
