# Generated by Django 5.0.3 on 2024-05-03 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_listing_allergen_choices_alter_listing_field_1"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="allergen_choices",
        ),
    ]
