# Generated by Django 5.0.3 on 2024-05-03 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_remove_listing_allergen_choices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="Listing_Tags",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="field_1",
        ),
    ]
