# Generated by Django 5.0.3 on 2024-05-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_remove_listing_listing_tags_remove_listing_field_1"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="user_profile",
        ),
        migrations.AddField(
            model_name="listing",
            name="slug",
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
