# Generated by Django 5.0.3 on 2024-05-03 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_remove_listing_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="user_profile",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="api.profile",
            ),
        ),
    ]
