# Generated by Django 5.0 on 2024-05-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_listing_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Listing_Cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3),
        ),
    ]
