# Generated by Django 5.0.3 on 2024-05-05 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_listing_listing_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="Listing_Author",
        ),
    ]
