# Generated by Django 5.0.3 on 2024-05-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_listing_listing_purchased"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="Listing_Area",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
    ]
