# Generated by Django 5.0.3 on 2024-05-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_listing_listing_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="Listing_Area",
            field=models.DecimalField(decimal_places=0, default=1, max_digits=4),
        ),
    ]
